server:
  port: 9000

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/fivchatter

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update