server:
  port: 9000

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./data/test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: 'smtp.mailtrap.io'
    port: 587
    username: 'a6df31fac163a7'
    password: '3c25f3e6dc6e28'
    from: 'info@authserver.com'
    fromName: 'Auth Server'
    sender: 'Auth Server Team'
    application-name: 'Auth Server Application'
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  freemarker:
    template-loader-path: 'classpath:/templates/emails/'

application:
  name: 'My Best App'
  url: 'http://localhost:9000'

authserver:
  registration:
    enable: true
    verification: true
  login:
    verification: true
    twoFactorEnable: false
  jwt:
    secretKey: 1234567890123456
    authKey: 1234567890123456