server:
  port: 9000

spring:
  datasource:
    username: WJ1LtlzdkN
    password: 803fbTAcYy
    url: jdbc:mysql://remotemysql.com:3306/WJ1LtlzdkN

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update